### ISSUE TITLE
How do I make use of SSL on Netty?

### ISSUE THREAD

**Issue by iamjhanders** [TransEmpiric/webFluxTemplate#1]

**Comment by SlowBurner** [comment]
You just need to change the "server.ssl.enabled" property to "true" in the in application.yml
`server:
  port: 8443
  ssl:
    enabled: true`

**Comment by iamjhanders** [comment]
Got it working, ty!

**Comment by chrissorens** [comment]
Hey Rob,

Can you call or text?  I lost my phone, I have a new one now but do not
have your number anymore.

-Chris
